# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidgt(object):
    def setupUi(self, MainWidgt):
        MainWidgt.setObjectName("MainWidgt")
        MainWidgt.resize(691, 372)
        MainWidgt.setWindowOpacity(1.0)
        MainWidgt.setToolTip("")
        self.pushButton_0 = QtWidgets.QPushButton(MainWidgt)
        self.pushButton_0.setGeometry(QtCore.QRect(60, 40, 91, 23))
        self.pushButton_0.setObjectName("pushButton_0")
        self.input_edit = QtWidgets.QLineEdit(MainWidgt)
        self.input_edit.setGeometry(QtCore.QRect(200, 40, 391, 20))
        self.input_edit.setObjectName("input_edit")
        self.pushButton_1 = QtWidgets.QPushButton(MainWidgt)
        self.pushButton_1.setGeometry(QtCore.QRect(60, 100, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(MainWidgt)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 160, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MainWidgt)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 220, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.input_file_label = QtWidgets.QLabel(MainWidgt)
        self.input_file_label.setGeometry(QtCore.QRect(60, 70, 141, 16))
        self.input_file_label.setObjectName("input_file_label")
        self.pushButton_4 = QtWidgets.QPushButton(MainWidgt)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 280, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(MainWidgt)
        self.textEdit.setGeometry(QtCore.QRect(203, 90, 391, 201))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.CancelButton = QtWidgets.QPushButton(MainWidgt)
        self.CancelButton.setGeometry(QtCore.QRect(570, 330, 75, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.label_0 = QtWidgets.QLabel(MainWidgt)
        self.label_0.setGeometry(QtCore.QRect(60, 130, 131, 16))
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")
        self.label_2 = QtWidgets.QLabel(MainWidgt)
        self.label_2.setGeometry(QtCore.QRect(60, 250, 131, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWidgt)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 131, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(MainWidgt)
        self.label_1.setGeometry(QtCore.QRect(60, 190, 131, 20))
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")

        self.retranslateUi(MainWidgt)
        QtCore.QMetaObject.connectSlotsByName(MainWidgt)

    def retranslateUi(self, MainWidgt):
        _translate = QtCore.QCoreApplication.translate
        MainWidgt.setWindowTitle(_translate("MainWidgt", "114514"))
        self.pushButton_0.setText(_translate("MainWidgt", "输入文件路径:"))
        self.pushButton_1.setText(_translate("MainWidgt", "分离音乐"))
        self.pushButton_2.setText(_translate("MainWidgt", "输出乐谱"))
        self.pushButton_3.setText(_translate("MainWidgt", "输出歌词"))
        self.input_file_label.setText(_translate("MainWidgt", "当前无路径"))
        self.pushButton_4.setText(_translate("MainWidgt", "输出歌名"))
        self.CancelButton.setText(_translate("MainWidgt", "Cancel"))
